config/routes.rb
Rails.application.routes.draw do
  
  resources :pontos do
      collection do
          get 'entrada'
          get 'saida'
      end
  end

  root to: "home#index"
  
  get 'home/index'

  devise_for :users, controllers: {registrations: "registrations"}

end

app/models/ponto.rb
class Ponto < ActiveRecord::Base

  belongs_to :user

  validates :user_id,  presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :pontos

  validates :name, presence: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/pontos_controller.rb
class PontosController < ApplicationController
  before_action :set_ponto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /pontos
  # GET /pontos.json
  def index
    @pontos = Ponto.where(user: current_user,data: Date.current.beginning_of_month .. Date.current.end_of_month)
    #@pontos = Ponto.all

  end

  # GET /pontos/1
  # GET /pontos/1.json




  def show
  end

  # GET /pontos/new
  def new
     @ponto = Ponto.where(user: current_user, saida: nil ).last
    if @ponto.nil?

        @ponto = Ponto.new
        render :entrada
    else
        render :saida
    end
  end

  # GET /pontos/1/edit
  def edit
  end

  # POST /pontos
  # POST /pontos.json
  def create
    @ponto = Ponto.new(ponto_params)
    @ponto.user = current_user

    respond_to do |format|
      if @ponto.save
        format.html { redirect_to @ponto, notice: 'Ponto was successfully created.' }
        format.json { render :show, status: :created, location: @ponto }
      else
        format.html { render :new }
        format.json { render json: @ponto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pontos/1
  # PATCH/PUT /pontos/1.json
  def update
    respond_to do |format|
      if @ponto.update(ponto_params)
        format.html { redirect_to @ponto, notice: 'Ponto was successfully updated.' }
        format.json { render :show, status: :ok, location: @ponto }
      else
        format.html { render :edit }
        format.json { render json: @ponto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pontos/1
  # DELETE /pontos/1.json
  def destroy
    @ponto.destroy
    respond_to do |format|
      format.html { redirect_to pontos_url, notice: 'Ponto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def entrada
  end

  def saida
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ponto
      @ponto = Ponto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ponto_params
      params.require(:ponto).permit(:data, :entrada, :saida)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    before_filter :update_sanitized_params, if: :devise_controller?

    def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pontos_helper.rb
module PontosHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%=link_to "registar pontos ", pontos_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NovaFrequencia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
    <%= "bem vindo, #{current_user.name}" %>
    <%= link_to "sair", destroy_user_session_path, method: :delete %>
<%else%>
    <%=link_to "entrar", new_user_session_path %>
<%end%>

<%= yield %>
    

</body>
</html>

app/views/pontos/_entrada_form.html.erb
<%= form_for(@ponto) do |f| %>
  <% if @ponto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ponto.errors.count, "error") %> prohibited this ponto from being saved:</h2>

      <ul>
      <% @ponto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :entrada %><br>
    <%= f.time_select :entrada %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pontos/_form.html.erb
<%= form_for(@ponto) do |f| %>
  <% if @ponto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ponto.errors.count, "error") %> prohibited this ponto from being saved:</h2>

      <ul>
      <% @ponto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :entrada %><br>
    <%= f.time_select :entrada %>
  </div>
  <div class="field">
    <%= f.label :saida %><br>
    <%= f.time_select :saida %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pontos/_saida_form.html.erb
<%= form_for(@ponto) do |f| %>
  <% if @ponto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ponto.errors.count, "error") %> prohibited this ponto from being saved:</h2>

      <ul>
      <% @ponto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>

  <div class="field">
    <%= f.label :saida %><br>
    <%= f.time_select :saida %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pontos/edit.html.erb
<h1>Editing ponto</h1>

<%= render 'form' %>

<%= link_to 'Show', @ponto %> |
<%= link_to 'Back', pontos_path %>

app/views/pontos/entrada.html.erb
<h1>New ponto</h1>

<%= render 'entrada_form' %>

<%= link_to 'Back', pontos_path %>

app/views/pontos/index.html.erb
<h1>Listing pontos</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Entrada</th>
      <th>Saida</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pontos.each do |ponto| %>
      <tr>
        <td><%= ponto.data %></td>
        <td><%= ponto.entrada %></td>
        <td><%= ponto.saida %></td>
        <td><%= link_to 'Show', ponto %></td>
        <td><%= link_to 'Edit', edit_ponto_path(ponto) %></td>
        <td><%= link_to 'Destroy', ponto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ponto', new_ponto_path %>

app/views/pontos/new.html.erb
<h1>New ponto</h1>

<%= render 'form' %>

<%= link_to 'Back', pontos_path %>

app/views/pontos/saida.html.erb
<h1>Editing ponto</h1>

<%= render 'saida_form' %>

<%= link_to 'Show', @ponto %> |
<%= link_to 'Back', pontos_path %>

app/views/pontos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @ponto.data %>
</p>

<p>
  <strong>Entrada:</strong>
  <%= @ponto.entrada %>
</p>

<p>
  <strong>Saida:</strong>
  <%= @ponto.saida %>
</p>

<%= link_to 'Edit', edit_ponto_path(@ponto) %> |
<%= link_to 'Back', pontos_path %>